apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-demo-new-api
  description: API for backstage-demo-new
spec:
  type: openapi
  lifecycle: production
  owner: team
  definition: |
    openapi: 3.0.0
    info:
      title: backstage-demo-new API
      version: 1.0.0
    paths: {}
