apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bjnkml-api
  description: API for bjnkml
spec:
  type: openapi
  lifecycle: production
  owner: team
  definition: |
    openapi: 3.0.0
    info:
      title: bjnkml API
      version: 1.0.0
    paths: {}
