apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-backend-api
  description: API for customer-backend
spec:
  type: openapi
  lifecycle: production
  owner: team
  definition: |
    openapi: 3.0.0
    info:
      title: customer-backend API
      version: 1.0.0
    paths: {}
