apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sairam-sairam-api
  description: API for sairam-sairam
spec:
  type: openapi
  lifecycle: production
  owner: team
  definition: |
    openapi: 3.0.0
    info:
      title: sairam-sairam API
      version: 1.0.0
    paths: {}
