apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: root-catalog
spec:
  targets:
  # Components
  - ./components/2kactingdrivers.yaml
  - ./components/acting-drivers-trichy.yaml
  - ./components/angular-sample-template.yaml
  - ./components/backstage-angular.yaml
  - ./components/backstage-catalog-sample.yaml
  - ./components/backstage-catalog-sample2.yaml
  - ./components/backstage-demo-new.yaml
  - ./components/backstage-demo-sairam.yaml
  - ./components/backstage-node.yaml
  - ./components/billing-software.yaml
  - ./components/billing-ui.yaml
  - ./components/bjnkml.yaml
  - ./components/customer.yaml
  - ./components/customer-backend.yaml
  - ./components/sairam.yaml
  - ./components/sairam-sairam.yaml
  - ./components/sairam-test.yaml
  - ./components/seller-rocket.yaml
  - ./components/template-structure.yaml

  # APIs
  - ./apis/2kactingdrivers-api.yaml
  - ./apis/acting-drivers-trichy-api.yaml
  - ./apis/angular-sample-template-api.yaml
  - ./apis/backstage-angular-api.yaml
  - ./apis/backstage-catalog-sample-api.yaml
  - ./apis/backstage-catalog-sample2-api.yaml
  - ./apis/backstage-demo-new-api.yaml
  - ./apis/backstage-demo-sairam-api.yaml
  - ./apis/backstage-node-api.yaml
  - ./apis/billing-software-api.yaml
  - ./apis/billing-ui-api.yaml
  - ./apis/bjnkml-api.yaml
  - ./apis/customer-api.yaml
  - ./apis/customer-backend-api.yaml
  - ./apis/sairam-api.yaml
  - ./apis/sairam-sairam-api.yaml
  - ./apis/sairam-test-api.yaml
  - ./apis/seller-rocket-api.yaml
  - ./apis/template-structure-api.yaml

  # Shared Entities
  - ./resources/mongodb.yaml
  - ./groups/team.yaml