apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2kactingdrivers
  description: "Acting driver booking application"
  annotations:
    github.com/project-slug: sairam3333/2KActingdrivers
    backstage.io/source-location: url:https://github.com/sairam3333/2KActingdrivers
    backstage.io/view-url: https://github.com/sairam3333/2KActingdrivers
spec:
  type: service
  lifecycle: production
  owner: Main Team

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - 2kactingdrivers-api
