apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: angular-sample-template
  description: "angular-sample-template repository"
  tags:
    - backstage
  annotations:
    github.com/project-slug: sairam3333/angular-sample-template
    backstage.io/source-location: url:https://github.com/sairam3333/angular-sample-template
    backstage.io/view-url: https://github.com/sairam3333/angular-sample-template
spec:
  type: website
  lifecycle: production
  owner: team

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - angular-sample-template-api
