apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo-sairam
  description: "backstage-demo-sairam"
  tags:
    - backstage
    - microservice
  annotations:
    github.com/project-slug: sairam3333/backstage-demo-sairam
    backstage.io/source-location: url:https://github.com/sairam3333/backstage-demo-sairam
    backstage.io/view-url: https://github.com/sairam3333/backstage-demo-sairam
spec:
  type: service
  lifecycle: production
  owner: team

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - backstage-demo-sairam-api
