apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-ui
  description: "billing-ui repository"
  tags:
    - backstage
  annotations:
    github.com/project-slug: sairam3333/billing-ui
    backstage.io/source-location: url:https://github.com/sairam3333/billing-ui
    backstage.io/view-url: https://github.com/sairam3333/billing-ui
spec:
  type: website
  lifecycle: production
  owner: team

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - billing-ui-api
