apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bjnkml
  description: "gbhjlk"
  tags:
    - typescript
    - html
    - scss
  annotations:
    github.com/project-slug: sairam3333/bjnkml
    backstage.io/source-location: url:https://github.com/sairam3333/bjnkml
    backstage.io/view-url: https://github.com/sairam3333/bjnkml
spec:
  type: service
  lifecycle: production
  owner: team

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - bjnkml-api
