apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: seller-rocket
  description: "task given by seller rocket"
  annotations:
    github.com/project-slug: sairam3333/seller-rocket
    backstage.io/source-location: url:https://github.com/sairam3333/seller-rocket
    backstage.io/view-url: https://github.com/sairam3333/seller-rocket
spec:
  type: service
  lifecycle: production
  owner: team

  dependsOn:
    - resource:default/mongodb

  providesApis:
    - seller-rocket-api
